# These are supported funding model platforms

github: [user1, user2, user3, user4] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: YassinosCoder
ko_fi: ko-fi-username # Replace with a single Ko-fi username
tidelift: npm/babel # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: cloud-foundry # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: liberapay-username # Replace with a single Liberapay username
issuehunt: issuehunt-username # Replace with a single IssueHunt username
otechie: otechie-username # Replace with a single Otechie username
lfx_crowdfunding: lfx-crowdfunding-project # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
custom: ['paypal.me/YassineSilver']
